package mx.edu.tecnm.semantico;

public enum TipoToken {
    // Palabras reservadas
    PUBLICO, PRIVADO, CLASE, ESTATICO, VACIO, PRINCIPAL,
    ENTERO, DECIMAL, CADENA, BOOLEANO,
    VERDADERO, FALSO, IMPRIMIR, SI, SINO, MIENTRAS, INICIO, FIN,

    // Identificadores y literales
    IDENTIFICADOR, NUMERO_ENTERO, NUMERO_DECIMAL, TEXTO,

    // Símbolos
    PARENTESIS_IZQ, PARENTESIS_DER,
    CORCHETE_IZQ, CORCHETE_DER,
    PUNTO_COMA, COMA,
    MAS, MENOS, ASTERISCO, DIAGONAL, MODULO,
    ASIGNACION, IGUAL_IGUAL, DIFERENTE,
    MENOR, MENOR_IGUAL, MAYOR, MAYOR_IGUAL,
    Y_LOGICO, O_LOGICO, NEGACION,

    EOF
}
